name: Build-Java-Library

permissions:
  id-token: write

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository code
      - name: Checkout code
        uses: actions/checkout@v3
      # Set up JDK (Java Development Kit)
      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          distribution: 'corretto'
          java-version: '21'  # You can change this to '8', '17', etc., depending on your project

      - name: Setup JFrog CLI
        uses: jfrog/setup-jfrog-cli@v4
        id: setup-jfrog-cli
        env:
          JF_URL: ${{ vars.JF_URL }}
        with:
          oidc-provider-name: github-oidc-integration
          oidc-audience: jfrog-github

      # Cache Maven dependencies for faster builds
      - name: Cache Maven packages
        uses: actions/cache@v3
        with:
          path: ~/.m2
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Configure Maven
        shell: bash
        run: |
          jf mvnc \
          --server-id-resolve=setup-jfrog-cli-server \
          --server-id-deploy=setup-jfrog-cli-server \
          --repo-resolve-releases=mavencentral-remote \
          --repo-resolve-snapshots=mavencentral-remote \
          --repo-deploy-releases=tomj-time-lib-maven-release-local \
          --repo-deploy-snapshots=tomj-time-lib-maven-snapshot-local

      - name: Build Library
        run: |
          jf mvn clean install --project tomj-time-lib


